"""add users

Revision ID: 2d4d1c947995
Revises: 759b9b1afcb5
Create Date: 2025-07-23 15:49:06.068236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4d1c947995'
down_revision: Union[str, Sequence[str], None] = '759b9b1afcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('program_code', sa.String(), nullable=False),
    sa.Column('applicant_id', sa.String(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('vi_score', sa.Integer(), nullable=False),
    sa.Column('subject1_score', sa.Integer(), nullable=False),
    sa.Column('subject2_score', sa.Integer(), nullable=False),
    sa.Column('id_achievements', sa.Integer(), nullable=False),
    sa.Column('target_id_achievements', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.id'], ),
    sa.ForeignKeyConstraint(['program_code'], ['programs.code'], ),
    sa.PrimaryKeyConstraint('program_code', 'applicant_id')
    )
    op.create_table('submission_stats',
    sa.Column('program_code', sa.String(), nullable=False),
    sa.Column('num_places', sa.Integer(), nullable=False),
    sa.Column('num_applications', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_code'], ['programs.code'], ),
    sa.PrimaryKeyConstraint('program_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_stats')
    op.drop_table('applications')
    op.drop_table('applicants')
    # ### end Alembic commands ###
